# Generated by Django 4.2.20 on 2025-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('price_usd', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('username', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('image_url', models.URLField(max_length=500)),
                ('images_count', models.IntegerField()),
                ('car_number', models.CharField(blank=True, max_length=500, null=True)),
                ('car_vin', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime_found', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='scraper_car_url_b0cc24_idx'), models.Index(fields=['car_vin'], name='scraper_car_car_vin_2b653f_idx'), models.Index(fields=['datetime_found'], name='scraper_car_datetim_0b3fc5_idx')],
                'unique_together': {('url', 'car_vin')},
            },
        ),
    ]
